language: ruby
sudo: false
bundler: true

rvm:
  - 2.3
  - 2.4
  - ruby-head

cache:
  bundler: true
  yarn: true

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

install:
  - bundle install
  - yarn install

script:
  - bundle exec rake
  - yarn lint
